<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjut</name>
   <tag></tag>
   <elementGuidId>22034a3a-24a2-4c7d-8239-b2259a72bc3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18779f91-df20-4efb-a43e-d8db99fdf2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-button bl-button--primary bl-button--medium bl-button--block</value>
      <webElementGuid>3f891c65-0f15-4dfd-bc77-9a8897c6fb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit_button</value>
      <webElementGuid>4c0da69a-a1c3-413d-b914-fb673d5fcf0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lanjut </value>
      <webElementGuid>ffdd67b1-9dd8-46fd-a57d-0c8d0534c2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit_button&quot;)</value>
      <webElementGuid>650b1538-25cd-4af3-be9d-85080409be8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit_button']</value>
      <webElementGuid>69178ac7-3dc7-49b4-9c9e-989bfad9cc20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor handphone atau email'])[1]/following::button[1]</value>
      <webElementGuid>437f5cb7-dce6-4189-9049-b635df416767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/preceding::button[1]</value>
      <webElementGuid>648be103-2973-4dee-9b5c-66f216e79e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ca4417fd-7a81-42d7-a12c-16ab6ca2bbba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'submit_button' and (text() = ' Lanjut ' or . = ' Lanjut ')]</value>
      <webElementGuid>89a87e67-56ec-44ce-84c6-0b497e56365b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
